version: '3.7'
services:
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/pgsql/data
    environment:
      - POSTGRES_PASSWORD=century
      - POSTGRES_USER=century
      - POSTGRES_DB=db

  node-app:
    build: ./gate-simulator
    image: node-app:1.0
    container_name: js-container
    ports:
      - '9999:9999'